server:
  port: 8443
  ssl:
    key-store: file:/Users/tjikaljedy/Workspace/SSL/dev/melody-io.p12
    key-store-password: changeit
---
core-config:
  rsocket-fs:
    enabled: true
    host: 127.0.0.1
    port: 6565